// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/feedback.proto

package feedback

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PassengerID struct {
	PassengerID          int32    `protobuf:"varint,1,opt,name=passengerID,proto3" json:"passengerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PassengerID) Reset()         { *m = PassengerID{} }
func (m *PassengerID) String() string { return proto.CompactTextString(m) }
func (*PassengerID) ProtoMessage()    {}
func (*PassengerID) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a8d20d2126ba5d, []int{0}
}

func (m *PassengerID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PassengerID.Unmarshal(m, b)
}
func (m *PassengerID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PassengerID.Marshal(b, m, deterministic)
}
func (m *PassengerID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PassengerID.Merge(m, src)
}
func (m *PassengerID) XXX_Size() int {
	return xxx_messageInfo_PassengerID.Size(m)
}
func (m *PassengerID) XXX_DiscardUnknown() {
	xxx_messageInfo_PassengerID.DiscardUnknown(m)
}

var xxx_messageInfo_PassengerID proto.InternalMessageInfo

func (m *PassengerID) GetPassengerID() int32 {
	if m != nil {
		return m.PassengerID
	}
	return 0
}

type BookingCode struct {
	BookingCode          string   `protobuf:"bytes,1,opt,name=bookingCode,proto3" json:"bookingCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookingCode) Reset()         { *m = BookingCode{} }
func (m *BookingCode) String() string { return proto.CompactTextString(m) }
func (*BookingCode) ProtoMessage()    {}
func (*BookingCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a8d20d2126ba5d, []int{1}
}

func (m *BookingCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookingCode.Unmarshal(m, b)
}
func (m *BookingCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookingCode.Marshal(b, m, deterministic)
}
func (m *BookingCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookingCode.Merge(m, src)
}
func (m *BookingCode) XXX_Size() int {
	return xxx_messageInfo_BookingCode.Size(m)
}
func (m *BookingCode) XXX_DiscardUnknown() {
	xxx_messageInfo_BookingCode.DiscardUnknown(m)
}

var xxx_messageInfo_BookingCode proto.InternalMessageInfo

func (m *BookingCode) GetBookingCode() string {
	if m != nil {
		return m.BookingCode
	}
	return ""
}

type Feedback struct {
	BookingCode          string   `protobuf:"bytes,1,opt,name=bookingCode,proto3" json:"bookingCode,omitempty"`
	PassengerID          int32    `protobuf:"varint,2,opt,name=passengerID,proto3" json:"passengerID,omitempty"`
	Feedback             string   `protobuf:"bytes,3,opt,name=feedback,proto3" json:"feedback,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Feedback) Reset()         { *m = Feedback{} }
func (m *Feedback) String() string { return proto.CompactTextString(m) }
func (*Feedback) ProtoMessage()    {}
func (*Feedback) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a8d20d2126ba5d, []int{2}
}

func (m *Feedback) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Feedback.Unmarshal(m, b)
}
func (m *Feedback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Feedback.Marshal(b, m, deterministic)
}
func (m *Feedback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feedback.Merge(m, src)
}
func (m *Feedback) XXX_Size() int {
	return xxx_messageInfo_Feedback.Size(m)
}
func (m *Feedback) XXX_DiscardUnknown() {
	xxx_messageInfo_Feedback.DiscardUnknown(m)
}

var xxx_messageInfo_Feedback proto.InternalMessageInfo

func (m *Feedback) GetBookingCode() string {
	if m != nil {
		return m.BookingCode
	}
	return ""
}

func (m *Feedback) GetPassengerID() int32 {
	if m != nil {
		return m.PassengerID
	}
	return 0
}

func (m *Feedback) GetFeedback() string {
	if m != nil {
		return m.Feedback
	}
	return ""
}

type ArrayFeedback struct {
	ArrayFeedback        []*Feedback `protobuf:"bytes,1,rep,name=arrayFeedback,proto3" json:"arrayFeedback,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ArrayFeedback) Reset()         { *m = ArrayFeedback{} }
func (m *ArrayFeedback) String() string { return proto.CompactTextString(m) }
func (*ArrayFeedback) ProtoMessage()    {}
func (*ArrayFeedback) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a8d20d2126ba5d, []int{3}
}

func (m *ArrayFeedback) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArrayFeedback.Unmarshal(m, b)
}
func (m *ArrayFeedback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArrayFeedback.Marshal(b, m, deterministic)
}
func (m *ArrayFeedback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArrayFeedback.Merge(m, src)
}
func (m *ArrayFeedback) XXX_Size() int {
	return xxx_messageInfo_ArrayFeedback.Size(m)
}
func (m *ArrayFeedback) XXX_DiscardUnknown() {
	xxx_messageInfo_ArrayFeedback.DiscardUnknown(m)
}

var xxx_messageInfo_ArrayFeedback proto.InternalMessageInfo

func (m *ArrayFeedback) GetArrayFeedback() []*Feedback {
	if m != nil {
		return m.ArrayFeedback
	}
	return nil
}

type AddFeedbackResponse struct {
	BookingCode          string   `protobuf:"bytes,1,opt,name=bookingCode,proto3" json:"bookingCode,omitempty"`
	PassengerID          int32    `protobuf:"varint,2,opt,name=passengerID,proto3" json:"passengerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFeedbackResponse) Reset()         { *m = AddFeedbackResponse{} }
func (m *AddFeedbackResponse) String() string { return proto.CompactTextString(m) }
func (*AddFeedbackResponse) ProtoMessage()    {}
func (*AddFeedbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a8d20d2126ba5d, []int{4}
}

func (m *AddFeedbackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFeedbackResponse.Unmarshal(m, b)
}
func (m *AddFeedbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFeedbackResponse.Marshal(b, m, deterministic)
}
func (m *AddFeedbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFeedbackResponse.Merge(m, src)
}
func (m *AddFeedbackResponse) XXX_Size() int {
	return xxx_messageInfo_AddFeedbackResponse.Size(m)
}
func (m *AddFeedbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFeedbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddFeedbackResponse proto.InternalMessageInfo

func (m *AddFeedbackResponse) GetBookingCode() string {
	if m != nil {
		return m.BookingCode
	}
	return ""
}

func (m *AddFeedbackResponse) GetPassengerID() int32 {
	if m != nil {
		return m.PassengerID
	}
	return 0
}

type DeleteByPassengerIDResponse struct {
	DeletedCount         int32    `protobuf:"varint,1,opt,name=deletedCount,proto3" json:"deletedCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteByPassengerIDResponse) Reset()         { *m = DeleteByPassengerIDResponse{} }
func (m *DeleteByPassengerIDResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteByPassengerIDResponse) ProtoMessage()    {}
func (*DeleteByPassengerIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a8d20d2126ba5d, []int{5}
}

func (m *DeleteByPassengerIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteByPassengerIDResponse.Unmarshal(m, b)
}
func (m *DeleteByPassengerIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteByPassengerIDResponse.Marshal(b, m, deterministic)
}
func (m *DeleteByPassengerIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteByPassengerIDResponse.Merge(m, src)
}
func (m *DeleteByPassengerIDResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteByPassengerIDResponse.Size(m)
}
func (m *DeleteByPassengerIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteByPassengerIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteByPassengerIDResponse proto.InternalMessageInfo

func (m *DeleteByPassengerIDResponse) GetDeletedCount() int32 {
	if m != nil {
		return m.DeletedCount
	}
	return 0
}

func init() {
	proto.RegisterType((*PassengerID)(nil), "feedback.PassengerID")
	proto.RegisterType((*BookingCode)(nil), "feedback.BookingCode")
	proto.RegisterType((*Feedback)(nil), "feedback.Feedback")
	proto.RegisterType((*ArrayFeedback)(nil), "feedback.ArrayFeedback")
	proto.RegisterType((*AddFeedbackResponse)(nil), "feedback.AddFeedbackResponse")
	proto.RegisterType((*DeleteByPassengerIDResponse)(nil), "feedback.DeleteByPassengerIDResponse")
}

func init() { proto.RegisterFile("protobuf/feedback.proto", fileDescriptor_d0a8d20d2126ba5d) }

var fileDescriptor_d0a8d20d2126ba5d = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x4f, 0x4b, 0x4d, 0x4d, 0x49, 0x4a, 0x4c, 0xce, 0xd6, 0x03, 0x8b,
	0x08, 0x71, 0xc0, 0xf8, 0x4a, 0xfa, 0x5c, 0xdc, 0x01, 0x89, 0xc5, 0xc5, 0xa9, 0x79, 0xe9, 0xa9,
	0x45, 0x9e, 0x2e, 0x42, 0x0a, 0x5c, 0xdc, 0x05, 0x08, 0xae, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x6b,
	0x10, 0xb2, 0x10, 0x48, 0x83, 0x53, 0x7e, 0x7e, 0x76, 0x66, 0x5e, 0xba, 0x73, 0x7e, 0x4a, 0x2a,
	0x48, 0x43, 0x12, 0x82, 0x0b, 0xd6, 0xc0, 0x19, 0x84, 0x2c, 0xa4, 0x94, 0xc5, 0xc5, 0xe1, 0x06,
	0xb5, 0x8d, 0xb0, 0x6a, 0x74, 0x07, 0x30, 0x61, 0x38, 0x40, 0x48, 0x8a, 0x0b, 0xee, 0x7a, 0x09,
	0x66, 0xb0, 0x01, 0x08, 0xdf, 0x78, 0x72, 0xf1, 0x3a, 0x16, 0x15, 0x25, 0x56, 0xc2, 0x2d, 0xb4,
	0xe0, 0xe2, 0x4d, 0x44, 0x16, 0x90, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x36, 0x12, 0xd2, 0x83, 0x07,
	0x08, 0x4c, 0x26, 0x08, 0x55, 0xa1, 0x52, 0x24, 0x97, 0xb0, 0x63, 0x4a, 0x0a, 0x5c, 0x36, 0xb5,
	0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x95, 0x1a, 0x3e, 0x50, 0x72, 0xe4, 0x92, 0x76, 0x49, 0xcd, 0x49,
	0x2d, 0x49, 0x75, 0xaa, 0x44, 0x0a, 0x7b, 0xb8, 0x15, 0x4a, 0x5c, 0x3c, 0x29, 0x60, 0xe9, 0x14,
	0xe7, 0xfc, 0xd2, 0xbc, 0x12, 0x68, 0x24, 0xa0, 0x88, 0x19, 0x1d, 0x63, 0xe2, 0x12, 0x84, 0xeb,
	0x85, 0xfb, 0xd6, 0x93, 0x4b, 0xc4, 0x31, 0x25, 0x05, 0x53, 0x1c, 0x8b, 0x77, 0xa5, 0x64, 0x11,
	0x62, 0xd8, 0xfc, 0xe9, 0xc5, 0x25, 0xe1, 0x9e, 0x5a, 0x02, 0x13, 0x46, 0x71, 0xa8, 0x90, 0x28,
	0x42, 0x2b, 0x92, 0xb0, 0x94, 0x38, 0x92, 0x89, 0x28, 0x91, 0xe0, 0x8a, 0x66, 0x16, 0x72, 0xfa,
	0x41, 0x32, 0x0b, 0x49, 0x58, 0x0a, 0x8b, 0x8b, 0x85, 0x82, 0xb9, 0x84, 0xb1, 0x04, 0x1b, 0x2e,
	0xd7, 0xa8, 0x22, 0x84, 0xf1, 0x04, 0x76, 0x12, 0x1b, 0x38, 0x43, 0x18, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x0f, 0xd9, 0xe7, 0x38, 0x2b, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PassengerFeedbackClient is the client API for PassengerFeedback service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PassengerFeedbackClient interface {
	AddPassengerFeedback(ctx context.Context, in *Feedback, opts ...grpc.CallOption) (*AddFeedbackResponse, error)
	GetFeedbackByPassengerID(ctx context.Context, in *PassengerID, opts ...grpc.CallOption) (*ArrayFeedback, error)
	GetFeedbackByBookingCode(ctx context.Context, in *BookingCode, opts ...grpc.CallOption) (*Feedback, error)
	DeleteByPassengerID(ctx context.Context, in *PassengerID, opts ...grpc.CallOption) (*DeleteByPassengerIDResponse, error)
}

type passengerFeedbackClient struct {
	cc *grpc.ClientConn
}

func NewPassengerFeedbackClient(cc *grpc.ClientConn) PassengerFeedbackClient {
	return &passengerFeedbackClient{cc}
}

func (c *passengerFeedbackClient) AddPassengerFeedback(ctx context.Context, in *Feedback, opts ...grpc.CallOption) (*AddFeedbackResponse, error) {
	out := new(AddFeedbackResponse)
	err := c.cc.Invoke(ctx, "/feedback.PassengerFeedback/AddPassengerFeedback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passengerFeedbackClient) GetFeedbackByPassengerID(ctx context.Context, in *PassengerID, opts ...grpc.CallOption) (*ArrayFeedback, error) {
	out := new(ArrayFeedback)
	err := c.cc.Invoke(ctx, "/feedback.PassengerFeedback/GetFeedbackByPassengerID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passengerFeedbackClient) GetFeedbackByBookingCode(ctx context.Context, in *BookingCode, opts ...grpc.CallOption) (*Feedback, error) {
	out := new(Feedback)
	err := c.cc.Invoke(ctx, "/feedback.PassengerFeedback/GetFeedbackByBookingCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passengerFeedbackClient) DeleteByPassengerID(ctx context.Context, in *PassengerID, opts ...grpc.CallOption) (*DeleteByPassengerIDResponse, error) {
	out := new(DeleteByPassengerIDResponse)
	err := c.cc.Invoke(ctx, "/feedback.PassengerFeedback/DeleteByPassengerID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PassengerFeedbackServer is the server API for PassengerFeedback service.
type PassengerFeedbackServer interface {
	AddPassengerFeedback(context.Context, *Feedback) (*AddFeedbackResponse, error)
	GetFeedbackByPassengerID(context.Context, *PassengerID) (*ArrayFeedback, error)
	GetFeedbackByBookingCode(context.Context, *BookingCode) (*Feedback, error)
	DeleteByPassengerID(context.Context, *PassengerID) (*DeleteByPassengerIDResponse, error)
}

// UnimplementedPassengerFeedbackServer can be embedded to have forward compatible implementations.
type UnimplementedPassengerFeedbackServer struct {
}

func (*UnimplementedPassengerFeedbackServer) AddPassengerFeedback(ctx context.Context, req *Feedback) (*AddFeedbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPassengerFeedback not implemented")
}
func (*UnimplementedPassengerFeedbackServer) GetFeedbackByPassengerID(ctx context.Context, req *PassengerID) (*ArrayFeedback, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeedbackByPassengerID not implemented")
}
func (*UnimplementedPassengerFeedbackServer) GetFeedbackByBookingCode(ctx context.Context, req *BookingCode) (*Feedback, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeedbackByBookingCode not implemented")
}
func (*UnimplementedPassengerFeedbackServer) DeleteByPassengerID(ctx context.Context, req *PassengerID) (*DeleteByPassengerIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteByPassengerID not implemented")
}

func RegisterPassengerFeedbackServer(s *grpc.Server, srv PassengerFeedbackServer) {
	s.RegisterService(&_PassengerFeedback_serviceDesc, srv)
}

func _PassengerFeedback_AddPassengerFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Feedback)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerFeedbackServer).AddPassengerFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feedback.PassengerFeedback/AddPassengerFeedback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerFeedbackServer).AddPassengerFeedback(ctx, req.(*Feedback))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassengerFeedback_GetFeedbackByPassengerID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PassengerID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerFeedbackServer).GetFeedbackByPassengerID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feedback.PassengerFeedback/GetFeedbackByPassengerID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerFeedbackServer).GetFeedbackByPassengerID(ctx, req.(*PassengerID))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassengerFeedback_GetFeedbackByBookingCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookingCode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerFeedbackServer).GetFeedbackByBookingCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feedback.PassengerFeedback/GetFeedbackByBookingCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerFeedbackServer).GetFeedbackByBookingCode(ctx, req.(*BookingCode))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassengerFeedback_DeleteByPassengerID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PassengerID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerFeedbackServer).DeleteByPassengerID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feedback.PassengerFeedback/DeleteByPassengerID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerFeedbackServer).DeleteByPassengerID(ctx, req.(*PassengerID))
	}
	return interceptor(ctx, in, info, handler)
}

var _PassengerFeedback_serviceDesc = grpc.ServiceDesc{
	ServiceName: "feedback.PassengerFeedback",
	HandlerType: (*PassengerFeedbackServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPassengerFeedback",
			Handler:    _PassengerFeedback_AddPassengerFeedback_Handler,
		},
		{
			MethodName: "GetFeedbackByPassengerID",
			Handler:    _PassengerFeedback_GetFeedbackByPassengerID_Handler,
		},
		{
			MethodName: "GetFeedbackByBookingCode",
			Handler:    _PassengerFeedback_GetFeedbackByBookingCode_Handler,
		},
		{
			MethodName: "DeleteByPassengerID",
			Handler:    _PassengerFeedback_DeleteByPassengerID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/feedback.proto",
}
